name: Calcular edad y etapa de vida

on:
  workflow_dispatch:
    inputs:
      anio:
        description: 'Año de nacimiento'
        required: true
      mes:
        description: 'Mes de nacimiento'
        required: true
      dia:
        description: 'Día de nacimiento'
        required: true

env:
  LIM_NINEZ: 13
  LIM_ADOLESCENCIA: 17
  LIM_ADULTO_JOVEN: 35
  LIM_ADULTO: 64

jobs:
  calcular-edad:
    name: Calcular Edad Detallada
    runs-on: ubuntu-latest
    outputs:
      edad_formato: ${{ steps.calcular.outputs.edad }}
      anios: ${{ steps.calcular.outputs.anios }}
    steps:
      - name: Calcular edad
        id: calcular
        run: |
          nacimiento="${{ github.event.inputs.anio }}-${{ github.event.inputs.mes }}-${{ github.event.inputs.dia }}"
          hoy=$(date +%Y-%m-%d)

          # Cálculo de diferencia
          anios=$(($(date -d "$hoy" +%Y) - $(date -d "$nacimiento" +%Y)))
          meses=$(($(date -d "$hoy" +%m) - $(date -d "$nacimiento" +%m)))
          dias=$(($(date -d "$hoy" +%d) - $(date -d "$nacimiento" +%d)))

          if [ "$dias" -lt 0 ]; then
            meses=$((meses - 1))
            dias=$((dias + 30))
          fi
          if [ "$meses" -lt 0 ]; then
            anios=$((anios - 1))
            meses=$((meses + 12))
          fi

          edad="${anios} anios, ${meses} meses, ${dias} días"
          echo "Edad calculada: $edad"

          echo "edad=$edad" >> $GITHUB_OUTPUT
          echo "anios=$anios" >> $GITHUB_OUTPUT

  clasificar-etapa:
    name: Clasificar Etapa de Vida
    runs-on: ubuntu-latest
    needs: calcular-edad
    steps:
      - name: Clasificación por edad
        run: |
          edad="${{ needs.calcular-edad.outputs.edad_formato }}"
          anios=${{ needs.calcular-edad.outputs.anios }}

          if [ "$anios" -le "${{ env.LIM_NINEZ }}" ]; then
            etapa="Niñez"
          elif [ "$anios" -le "${{ env.LIM_ADOLESCENCIA }}" ]; then
            etapa="Adolescencia"
          elif [ "$anios" -le "${{ env.LIM_ADULTO_JOVEN }}" ]; then
            etapa="Adultez Joven"
          elif [ "$anios" -le "${{ env.LIM_ADULTO }}" ]; then
            etapa="Adultez"
          else
            etapa="Vejez"
          fi

          echo "Edad: $edad"
          echo "Etapa de vida: $etapa"
