name: Suma de números

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  sumar:
    runs-on: ubuntu-latest
    steps:
      - name: Definir variables
        run: |
          NUM1=5
          NUM2=7
          echo "El primer número es $NUM1"
          echo "El segundo número es $NUM2"
          echo "RESULTADO=$((NUM1 + NUM2))" >> $GITHUB_ENV

      - name: Mostrar resultado
        run: echo "La suma es $RESULTADO"
Jobs:
  restar:
    
    runs-on: ubuntu-latest
    steps:
      - name: definir varables
        run: |
          NUM3=2
          NUM4=25
           echo "El resultado de la RESTA=$((NUM3 + NUM4))" >> $GITHUB_ENV

      -name: Mostrar resultados
     run: echo  " el resultado de la resta es $RESTA"

